export const JOHN_CHAPTER_20_WORDS_RAW = [
  { lemma: 'πρωΐ', textForm: 'πρωΐ', translation: 'рано утром', frequency: 12, verseRef: 'Ин 20:1', contextPhrase: 'πρωΐ σκοτίας ἔτι οὔσης', contextRu: 'рано, когда было еще темно' },
  { lemma: 'σκοτία', textForm: 'σκοτίας', translation: 'тьма, темнота', frequency: 17, verseRef: 'Ин 20:1', contextPhrase: 'σκοτίας ἔτι οὔσης', contextRu: 'когда было еще темно' },
  { lemma: 'μνημεῖον', textForm: 'μνημεῖον / μνημείου / μνημείῳ', translation: 'гробница, памятник', frequency: 40, verseRef: 'Ин 20:1', contextPhrase: 'εἰς τὸ μνημεῖον', contextRu: 'ко гробу' },
  { lemma: 'αἴρω', textForm: 'ἠρμένον / ἦραν / ᾖραν / ἆραι', translation: 'поднимаю, уношу, взял', frequency: 100, verseRef: 'Ин 20:1', contextPhrase: 'τὸν λίθον ἠρμένον', contextRu: 'камень отнятым' },
  { lemma: 'τρέχω', textForm: 'ἔτρεχεν / ἔτρεχον', translation: 'бегу, бежали', frequency: 20, verseRef: 'Ин 20:2', contextPhrase: 'τρέχει οὖν καὶ ἔρχεται', contextRu: 'итак бежит и приходит' },
  { lemma: 'φιλέω', textForm: 'ἐφίλει', translation: 'любил', frequency: 25, verseRef: 'Ин 20:2', contextPhrase: 'ὃν ἐφίλει ὁ Ἰησοῦς', contextRu: 'которого любил Иисус' },
  { lemma: 'ποῦ', textForm: 'ποῦ', translation: 'где? куда?', frequency: 48, verseRef: 'Ин 20:2', contextPhrase: 'οὐκ οἴδαμεν ποῦ ἔθηκαν αὐτόν', contextRu: 'не знаем, где положили Его' },
  { lemma: 'τίθημι', textForm: 'ἔθηκαν / ἔθηκας / ἔθηκεν', translation: 'положили, положил', frequency: 100, verseRef: 'Ин 20:2', contextPhrase: 'ποῦ ἔθηκαν αὐτόν', contextRu: 'где положили Его' },
  { lemma: 'προτρέχω', textForm: 'προέδραμεν', translation: 'бегу вперед, обгоняю', frequency: 2, verseRef: 'Ин 20:4', contextPhrase: 'προέδραμεν τάχιον τοῦ Πέτρου', contextRu: 'бежал скорее Петра' },
  { lemma: 'ταχέως', textForm: 'τάχιον', translation: 'быстрее, скорее', frequency: 10, verseRef: 'Ин 20:4', contextPhrase: 'τάχιον τοῦ Πέτρου', contextRu: 'скорее Петра' },
  { lemma: 'πρῶτος', textForm: 'πρῶτος', translation: 'первый, раньше', frequency: 97, verseRef: 'Ин 20:4', contextPhrase: 'ἦλθεν πρῶτος εἰς τὸ μνημεῖον', contextRu: 'пришел ко гробу первый' },
  { lemma: 'παρακύπτω', textForm: 'παρακύψας', translation: 'наклоняюсь, заглядываю внутрь', frequency: 5, verseRef: 'Ин 20:5', contextPhrase: 'καὶ παρακύψας βλέπει', contextRu: 'и, наклонившись, видит' },
  { lemma: 'κεῖμαι', textForm: 'κείμενα', translation: 'лежащие, лежат', frequency: 24, verseRef: 'Ин 20:5', contextPhrase: 'κείμενα τὰ ὀθόνια', contextRu: 'лежащие пелены' },
  { lemma: 'ὀθόνιον', textForm: 'ὀθόνια', translation: 'пелены, льняные ткани', frequency: 5, verseRef: 'Ин 20:5', contextPhrase: 'κείμενα τὰ ὀθόνια', contextRu: 'лежащие пелены' },
  { lemma: 'σουδάριον', textForm: 'σουδάριον', translation: 'плат, головная повязка', frequency: 5, verseRef: 'Ин 20:7', contextPhrase: 'καὶ τὸ σουδάριον', contextRu: 'и плат' },
  { lemma: 'χωρίς', textForm: 'χωρὶς', translation: 'отдельно, особо', frequency: 41, verseRef: 'Ин 20:7', contextPhrase: 'χωρὶς ἐντετυλιγμένον', contextRu: 'особо свитым' },
  { lemma: 'ἐντυλίσσω', textForm: 'ἐντετυλιγμένον', translation: 'свернутый, обвитый', frequency: 3, verseRef: 'Ин 20:7', contextPhrase: 'ἐντετυλιγμένον εἰς ἕνα τόπον', contextRu: 'свитым на другом месте' },
  { lemma: 'τόπος', textForm: 'τόπον', translation: 'место', frequency: 94, verseRef: 'Ин 20:7', contextPhrase: 'εἰς ἕνα τόπον', contextRu: 'на другом месте' },
  { lemma: 'οὐδέπω', textForm: 'οὐδέπω', translation: 'еще не', frequency: 28, verseRef: 'Ин 20:9', contextPhrase: 'οὐδέπω γὰρ ᾔδεισαν τὴν γραφήν', contextRu: 'ибо они еще не знали из Писания' },
  { lemma: 'δεῖ', textForm: 'δεῖ', translation: 'надлежит, должно', frequency: 101, verseRef: 'Ин 20:9', contextPhrase: 'ὅτι δεῖ αὐτὸν ἐκ νεκρῶν ἀναστῆναι', contextRu: 'что Ему надлежало воскреснуть' },
  { lemma: 'ἀνίστημι', textForm: 'ἀναστῆναι', translation: 'воскреснуть, восстать', frequency: 108, verseRef: 'Ин 20:9', contextPhrase: 'ἐκ νεκρῶν ἀναστῆναι', contextRu: 'из мертвых воскреснуть' },
  { lemma: 'κλαίω', textForm: 'κλαίουσα / κλαίεις', translation: 'плачущая, плачешь', frequency: 40, verseRef: 'Ин 20:11', contextPhrase: 'εἱστήκει πρὸς τῷ μνημείῳ ἔξω κλαίουσα', contextRu: 'стояла у гроба и плакала' },
  { lemma: 'λευκός', textForm: 'λευκοῖς', translation: 'белые', frequency: 23, verseRef: 'Ин 20:12', contextPhrase: 'δύο ἀγγέλους ἐν λευκοῖς', contextRu: 'двух Ангелов в белом' },
  { lemma: 'καθέζομαι', textForm: 'καθεζομένους', translation: 'сидящих', frequency: 87, verseRef: 'Ин 20:12', contextPhrase: 'καθεζομένους', contextRu: 'сидящих' },
  { lemma: 'στρέφω', textForm: 'ἐστράφη', translation: 'повернулась, обратилась', frequency: 21, verseRef: 'Ин 20:14', contextPhrase: 'ἐστράφη εἰς τὰ ὀπίσω', contextRu: 'обратилась назад' },
  { lemma: 'ὀπίσω', textForm: 'εἰς τὰ ὀπίσω', translation: 'назад, вспять', frequency: 35, verseRef: 'Ин 20:14', contextPhrase: 'εἰς τὰ ὀπίσω', contextRu: 'назад' },
  { lemma: 'κηπουρός', textForm: 'κηπουρός', translation: 'садовник', frequency: 1, verseRef: 'Ин 20:15', contextPhrase: 'δοκοῦσα ὅτι ὁ κηπουρός ἐστιν', contextRu: 'думая, что это садовник' },
  { lemma: 'βαστάζω', textForm: 'ἐβάστασας', translation: 'унес, взял', frequency: 27, verseRef: 'Ин 20:15', contextPhrase: 'εἰ σὺ ἐβάστασας αὐτόν', contextRu: 'если ты вынес Его' },
  { lemma: 'Ἑβραϊστί', textForm: 'Ἑβραϊστί', translation: 'по-еврейски (по-арамейски)', frequency: 7, verseRef: 'Ин 20:16', contextPhrase: 'λέγει αὐτῷ Ἑβραϊστί', contextRu: 'говорит Ему по-еврейски' },
  { lemma: 'ῥαββουνί', textForm: 'Ῥαββουνι', translation: 'Раббуни (Учитель мой)', frequency: 2, verseRef: 'Ин 20:16', contextPhrase: 'Ῥαββουνι', contextRu: 'Рабвуни' },
  { lemma: 'διδάσκαλος', textForm: 'διδάσκαλε', translation: 'Учитель', frequency: 59, verseRef: 'Ин 20:16', contextPhrase: 'ὃ λέγεται, Διδάσκαλε', contextRu: 'что значит: Учитель' },
  { lemma: 'ἅπτω', textForm: 'ἅπτου', translation: 'прикасайся, удерживай', frequency: 39, verseRef: 'Ин 20:17', contextPhrase: 'Μή μου ἅπτου', contextRu: 'Не прикасайся ко Мне' },
  { lemma: 'οὔπω', textForm: 'οὔπω', translation: 'еще не', frequency: 28, verseRef: 'Ин 20:17', contextPhrase: 'οὔπω γὰρ ἀναβέβηκα', contextRu: 'ибо Я еще не восшел' },
  { lemma: 'ἀναβαίνω', textForm: 'ἀναβέβηκα / ἀναβαίνω', translation: 'восшел, восхожу', frequency: 82, verseRef: 'Ин 20:17', contextPhrase: 'ἀναβαίνω πρὸς τὸν πατέρα μου', contextRu: 'восхожу к Отцу Моему' },
  { lemma: 'ἀπαγγέλλω', textForm: 'ἀγγέλλουσα / ἀπαγγέλλουσα', translation: 'возвещающая, возвещаю', frequency: 45, verseRef: 'Ин 20:18', contextPhrase: 'ἀγγέλλουσα τοῖς μαθηταῖς', contextRu: 'возвещая ученикам' },
  { lemma: 'ὀψία', textForm: 'ὀψίας', translation: 'вечер, поздно', frequency: 14, verseRef: 'Ин 20:19', contextPhrase: 'Οὔσης οὖν ὀψίας', contextRu: 'В тот же первый день недели вечером' },
  { lemma: 'θύρα', textForm: 'θυρῶν', translation: 'двери', frequency: 39, verseRef: 'Ин 20:19', contextPhrase: 'τῶν θυρῶν κεκλεισμένων', contextRu: 'когда двери были заперты' },
  { lemma: 'κλείω', textForm: 'κεκλεισμένων', translation: 'запертых, закрытых', frequency: 16, verseRef: 'Ин 20:19', contextPhrase: 'τῶν θυρῶν κεκλεισμένων', contextRu: 'двери были заперты' },
  { lemma: 'φόβος', textForm: 'φόβον', translation: 'страх', frequency: 47, verseRef: 'Ин 20:19', contextPhrase: 'διὰ τὸν φόβον τῶν Ἰουδαίων', contextRu: 'из опасения от Иудеев' },
  { lemma: 'μέσος', textForm: 'μέσον', translation: 'посередине', frequency: 58, verseRef: 'Ин 20:19', contextPhrase: 'καὶ ἔστη εἰς τὸ μέσον', contextRu: 'и стал посреди' },
  { lemma: 'εἰρήνη', textForm: 'εἰρήνη', translation: 'мир, покой', frequency: 91, verseRef: 'Ин 20:19', contextPhrase: 'Εἰρήνη ὑμῖν', contextRu: 'Мир вам' },
  { lemma: 'δείκνυμι', textForm: 'ἔδειξεν', translation: 'показал', frequency: 33, verseRef: 'Ин 20:20', contextPhrase: 'ἔδειξεν τὰς χεῖρας καὶ τὴν πλευρὰν', contextRu: 'показал им руки и ноги и ребра' },
  { lemma: 'πλευρά', textForm: 'πλευρὰν', translation: 'бок, ребра', frequency: 5, verseRef: 'Ин 20:20', contextPhrase: 'καὶ τὴν πλευρὰν', contextRu: 'и ребра' },
  { lemma: 'χαίρω', textForm: 'ἐχάρησαν', translation: 'обрадовались, возрадовались', frequency: 74, verseRef: 'Ин 20:20', contextPhrase: 'ἐχάρησαν οὖν οἱ μαθηταὶ', contextRu: 'Ученики обрадовались' },
  { lemma: 'καθώς', textForm: 'καθώς', translation: 'как, подобно тому как', frequency: 182, verseRef: 'Ин 20:21', contextPhrase: 'καθὼς ἀπέσταλκέν με ὁ πατήρ', contextRu: 'как послал Меня Отец' },
  { lemma: 'ἐμφυσάω', textForm: 'ἐνεφύσησεν', translation: 'дунул, подул', frequency: 1, verseRef: 'Ин 20:22', contextPhrase: 'καὶ τοῦτο εἰπὼν ἐνεφύσησεν', contextRu: 'Сказав это, дунул' },
  { lemma: 'ἀφίημι', textForm: 'ἀφίενται / ἀφέωνται', translation: 'прощаются, отпускаются', frequency: 143, verseRef: 'Ин 20:23', contextPhrase: 'ἀφέωνται αὐτοῖς', contextRu: 'простятся им' },
  { lemma: 'κρατέω', textForm: 'κεκράτηνται', translation: 'удерживаются, связаны', frequency: 47, verseRef: 'Ин 20:23', contextPhrase: 'ἄν τινων κρατῆτε, κεκράτηνται', contextRu: 'на ком оставите, на том останутся' },
  { lemma: 'Δίδυμος', textForm: 'Δίδυμος', translation: 'Близнец (Дидим)', frequency: 3, verseRef: 'Ин 20:24', contextPhrase: 'Θωμᾶς δὲ ... ὁ λεγόμενος Δίδυμος', contextRu: 'Фома же ... называемый Близнец' },
  { lemma: 'τύπος', textForm: 'τύπον', translation: 'след, отпечаток', frequency: 15, verseRef: 'Ин 20:25', contextPhrase: 'τὸν τύπον τῶν ἥλων', contextRu: 'раны от гвоздей' },
  { lemma: 'ἧλος', textForm: 'ἥλων', translation: 'гвозди', frequency: 1, verseRef: 'Ин 20:25', contextPhrase: 'τὸν τύπον τῶν ἥλων', contextRu: 'раны от гвоздей' },
  { lemma: 'δάκτυλος', textForm: 'δάκτυλόν', translation: 'палец', frequency: 8, verseRef: 'Ин 20:25', contextPhrase: 'βάλω τὸν δάκτυλόν μου', contextRu: 'вложу перст мой' },
  { lemma: 'βάλλω', textForm: 'βάλω / βάλε', translation: 'вложу, вложи', frequency: 122, verseRef: 'Ин 20:25', contextPhrase: 'βάλω τὸν δάκτυλόν μου', contextRu: 'вложу перст мой' },
  { lemma: 'ὀκτώ', textForm: 'ὀκτώ', translation: 'восемь', frequency: 9, verseRef: 'Ин 20:26', contextPhrase: 'μεθ’ ἡμέρας ὀκτὼ', contextRu: 'После восьми дней' },
  { lemma: 'ἔσω', textForm: 'ἔσω', translation: 'внутри', frequency: 8, verseRef: 'Ин 20:26', contextPhrase: 'πάλιν ἦσαν ἔσω οἱ μαθηταὶ', contextRu: 'опять были в доме ученики' },
  { lemma: 'ἄπιστος', textForm: 'ἄπιστος', translation: 'неверующий', frequency: 23, verseRef: 'Ин 20:27', contextPhrase: 'καὶ μὴ γίνου ἄπιστος', contextRu: 'и не будь неверующим' },
  { lemma: 'πιστός', textForm: 'πιστός', translation: 'верующий, верный', frequency: 67, verseRef: 'Ин 20:27', contextPhrase: 'ἀλλὰ πιστός', contextRu: 'но верующим' },
  { lemma: 'μακάριος', textForm: 'μακάριοι', translation: 'блаженны', frequency: 50, verseRef: 'Ин 20:29', contextPhrase: 'μακάριοι οἱ μὴ ἰδόντες', contextRu: 'блаженны не видевшие' },
  { lemma: 'σημεῖον', textForm: 'σημεῖα', translation: 'знамения, чудеса', frequency: 77, verseRef: 'Ин 20:30', contextPhrase: 'Πολλὰ μὲν οὖν καὶ ἄλλα σημεῖα', contextRu: 'Много сотворил Иисус пред учениками Своими и других чудес' },
  { lemma: 'βιβλίον', textForm: 'βιβλίῳ', translation: 'книга, свиток', frequency: 34, verseRef: 'Ин 20:30', contextPhrase: 'ἐν τῷ βιβλίῳ τούτῳ', contextRu: 'в книге сей' },
];
