export const JOHN_CHAPTER_19_WORDS_RAW = [
  { lemma: 'μαστιγόω', textForm: 'ἐμαστίγωσεν', translation: 'бичую, подвергаю бичеванию', frequency: 7, verseRef: 'Ин 19:1', contextPhrase: 'καὶ ἐμαστίγωσεν', contextRu: 'и бил Его (бичевал)' },
  { lemma: 'πλέκω', textForm: 'πλέξαντες', translation: 'плету, сплетаю', frequency: 3, verseRef: 'Ин 19:2', contextPhrase: 'πλέξαντες στέφανον', contextRu: 'сплетши венец' },
  { lemma: 'στέφανος', textForm: 'στέφανον', translation: 'венок, венец', frequency: 18, verseRef: 'Ин 19:2', contextPhrase: 'στέφανον ἐξ ἀκανθῶν', contextRu: 'венец из терна' },
  { lemma: 'ἄκανθα', textForm: 'ἀκανθῶν', translation: 'терние, колючки', frequency: 14, verseRef: 'Ин 19:2', contextPhrase: 'ἐξ ἀκανθῶν', contextRu: 'из терна' },
  { lemma: 'περιβάλλω', textForm: 'περιέβαλον', translation: 'надеваю, облачаю', frequency: 24, verseRef: 'Ин 19:2', contextPhrase: 'ἱμάτιον πορφυροῦν περιέβαλον αὐτὸν', contextRu: 'в багряницу одели Его' },
  { lemma: 'ἱμάτιον', textForm: 'ἱμάτιον', translation: 'одежда, мантия', frequency: 61, verseRef: 'Ин 19:2', contextPhrase: 'ἱμάτιον πορφυροῦν', contextRu: 'багряную одежду' },
  { lemma: 'πορφυροῦς', textForm: 'πορφυροῦν', translation: 'пурпурный, багряный', frequency: 3, verseRef: 'Ин 19:2', contextPhrase: 'ἱμάτιον πορφυροῦν', contextRu: 'багряную одежду' },
  { lemma: 'χαῖρε', textForm: 'χαῖρε', translation: 'радуйся! приветствуем!', frequency: 74, verseRef: 'Ин 19:3', contextPhrase: 'Χαῖρε ὁ βασιλεὺς', contextRu: 'Радуйся, Царь' },
  { lemma: 'ῥάπισμα', textForm: 'ῥαπίσματα', translation: 'удар по лицу, пощечина', frequency: 3, verseRef: 'Ин 19:3', contextPhrase: 'καὶ ἐδίδοσαν αὐτῷ ῥαπίσματα', contextRu: 'и били Его по ланитам' },
  { lemma: 'ἔξω', textForm: 'ἔξω', translation: 'наружу, вон', frequency: 63, verseRef: 'Ин 19:4', contextPhrase: 'ἄγω ὑμῖν αὐτὸν ἔξω', contextRu: 'вывожу Его к вам вон' },
  { lemma: 'αἰτία', textForm: 'αἰτίαν', translation: 'вина, причина', frequency: 20, verseRef: 'Ин 19:4', contextPhrase: 'οὐδεμίαν αἰτίαν εὑρίσκω', contextRu: 'не нахожу никакой вины' },
  { lemma: 'φορέω', textForm: 'φορῶν', translation: 'ношу, облачен', frequency: 6, verseRef: 'Ин 19:5', contextPhrase: 'φορῶν τὸν ἀκάνθινον στέφανον', contextRu: 'в терновом венце' },
  { lemma: 'ἀκάνθινος', textForm: 'ἀκάνθινον', translation: 'терновый', frequency: 2, verseRef: 'Ин 19:5', contextPhrase: 'τὸν ἀκάνθινον στέφανον', contextRu: 'терновый венец' },
  { lemma: 'ἴδε', textForm: 'ἴδε', translation: 'вот! смотри!', frequency: 29, verseRef: 'Ин 19:5', contextPhrase: 'Ἰδοὺ / ἴδε ὁ ἄνθρωπος', contextRu: 'Се, Человек' },
  { lemma: 'ὑπηρέτης', textForm: 'ὑπηρέται', translation: 'служители, стража', frequency: 20, verseRef: 'Ин 19:6', contextPhrase: 'οἱ ἀρχιερεῖς καὶ οἱ ὑπηρέται', contextRu: 'первосвященники и служители' },
  { lemma: 'κραυγάζω', textForm: 'ἐκραύγασαν', translation: 'закричали, завопили', frequency: 9, verseRef: 'Ин 19:6', contextPhrase: 'ἐκραύγασαν λέγοντες', contextRu: 'закричали, говоря' },
  { lemma: 'σταυρόω', textForm: 'σταύρωσον / σταυρωθῆναι / ἐσταύρωσαν', translation: 'распинаю', frequency: 46, verseRef: 'Ин 19:6', contextPhrase: 'Σταύρωσον σταύρωσον', contextRu: 'Распни, распни' },
  { lemma: 'ὀφείλω', textForm: 'ὀφείλει', translation: 'должен, обязан', frequency: 35, verseRef: 'Ин 19:7', contextPhrase: 'κατὰ τὸν νόμον ὀφείλει ἀποθανεῖν', contextRu: 'по закону должен умереть' },
  { lemma: 'ἀποθνήσκω', textForm: 'ἀποθανεῖν', translation: 'умирать', frequency: 111, verseRef: 'Ин 19:7', contextPhrase: 'ὀφείλει ἀποθανεῖν', contextRu: 'должен умереть' },
  { lemma: 'μᾶλλον', textForm: 'μᾶλλον', translation: 'больше, сильнее', frequency: 80, verseRef: 'Ин 19:8', contextPhrase: 'μᾶλλον ἐφοβήθη', contextRu: 'больше убоялся' },
  { lemma: 'φοβέομαι', textForm: 'ἐφοβήθη', translation: 'убоялся, устрашился', frequency: 95, verseRef: 'Ин 19:8', contextPhrase: 'μᾶλλον ἐφοβήθη', contextRu: 'больше убоялся' },
  { lemma: 'πραιτώριον', textForm: 'πραιτώριον', translation: 'претория, резиденция', frequency: 8, verseRef: 'Ин 19:9', contextPhrase: 'εἰσῆλθεν εἰς τὸ πραιτώριον', contextRu: 'вошел в преторию' },
  { lemma: 'πόθεν', textForm: 'πόθεν', translation: 'откуда?', frequency: 28, verseRef: 'Ин 19:9', contextPhrase: 'Πόθεν εἶ σύ;', contextRu: 'Откуда Ты?' },
  { lemma: 'ἄνωθεν', textForm: 'ἄνωθεν', translation: 'свыше, сверху', frequency: 13, verseRef: 'Ин 19:11', contextPhrase: 'εἰ μὴ ἦν δεδομένον σοι ἄνωθεν', contextRu: 'если бы не было дано тебе свыше' },
  { lemma: 'παραδίδωμι', textForm: 'παραδούς / παρέδωκεν', translation: 'предающий, передал', frequency: 119, verseRef: 'Ин 19:11', contextPhrase: 'ὁ παραδούς μέ σοι', contextRu: 'предавший Меня тебе' },
  { lemma: 'μείζων', textForm: 'μείζονα', translation: 'больший, более тяжкий', frequency: 196, verseRef: 'Ин 19:11', contextPhrase: 'μείζονα ἁμαρτίαν ἔχει', contextRu: 'более тяжкий грех имеет' },
  { lemma: 'ἀπολύω', textForm: 'ἀπολῦσαι', translation: 'отпустить, освободить', frequency: 66, verseRef: 'Ин 19:12', contextPhrase: 'ἐζήτει ἀπολῦσαι αὐτόν', contextRu: 'искал отпустить Его' },
  { lemma: 'κράζω', textForm: 'ἔκραζον', translation: 'кричали, вопили', frequency: 55, verseRef: 'Ин 19:12', contextPhrase: 'οἱ δὲ Ἰουδαῖοι ἔκραζον', contextRu: 'Иудеи же кричали' },
  { lemma: 'φίλος', textForm: 'φίλος', translation: 'друг', frequency: 29, verseRef: 'Ин 19:12', contextPhrase: 'οὐκ εἶ φίλος τοῦ Καίσαρος', contextRu: 'ты не друг кесарю' },
  { lemma: 'ἀντιλέγω', textForm: 'ἀντιλέγει', translation: 'противоречит, противится', frequency: 8, verseRef: 'Ин 19:12', contextPhrase: 'ἀντιλέγει τῷ Καίσαρι', contextRu: 'противится кесарю' },
  { lemma: 'βῆμα', textForm: 'βήματος', translation: 'судейское место, трибунал', frequency: 12, verseRef: 'Ин 19:13', contextPhrase: 'ἐκάθισεν ἐπὶ βήματος', contextRu: 'сел на судилище' },
  { lemma: 'λιθόστρωτος', textForm: 'λιθόστρωτον', translation: 'мощеная камнем площадка (лифостротон)', frequency: 1, verseRef: 'Ин 19:13', contextPhrase: 'εἰς τόπον λεγόμενον Λιθόστρωτον', contextRu: 'на место, называемое Лифостротон' },
  { lemma: 'Ἑβραϊστί', textForm: 'Ἑβραϊστὶ', translation: 'по-еврейски (на арамейском)', frequency: 7, verseRef: 'Ин 19:13', contextPhrase: 'Ἑβραϊστὶ δὲ Γαββαθά', contextRu: 'а по-еврейски Гавфафа' },
  { lemma: 'παρασκευή', textForm: 'παρασκευὴ', translation: 'приготовление (канун субботы/праздника)', frequency: 6, verseRef: 'Ин 19:14', contextPhrase: 'ἦν δὲ παρασκευὴ τοῦ πάσχα', contextRu: 'была же пятница пред Пасхою' },
  { lemma: 'πάσχα', textForm: 'πάσχα', translation: 'пасха', frequency: 29, verseRef: 'Ин 19:14', contextPhrase: 'παρασκευὴ τοῦ πάσχα', contextRu: 'пятница пред Пасхою' },
  { lemma: 'ἕκτος', textForm: 'ἕκτη', translation: 'шестой', frequency: 14, verseRef: 'Ин 19:14', contextPhrase: 'ὥρα ἦν ὡς ἕκτη', contextRu: 'был час около шестого' },
  { lemma: 'αἴρω', textForm: 'ἆρον', translation: 'убей, возьми прочь', frequency: 100, verseRef: 'Ин 19:15', contextPhrase: 'Ἆρον ἆρον, σταύρωσον αὐτόν', contextRu: 'Возьми, возьми, распни Его' },
  { lemma: 'βαστάζω', textForm: 'βαστάζων', translation: 'неся, неся на себе', frequency: 27, verseRef: 'Ин 19:17', contextPhrase: 'καὶ βαστάζων ἑαυτῷ τὸν σταυρὸν', contextRu: 'и, неся крест Свой' },
  { lemma: 'σταυρός', textForm: 'σταυρόν / σταυροῦ / σταυρῷ', translation: 'крест', frequency: 27, verseRef: 'Ин 19:17', contextPhrase: 'βαστάζων ... τὸν σταυρὸν', contextRu: 'неся ... крест' },
  { lemma: 'κρανίον', textForm: 'κρανίου', translation: 'череп (лобное место)', frequency: 4, verseRef: 'Ин 19:17', contextPhrase: 'Κρανίου Τόπον', contextRu: 'Лобное место' },
  { lemma: 'ἐντεῦθεν', textForm: 'ἐντεῦθεν καὶ ἐντεῦθεν', translation: 'по ту и по другую сторону', frequency: 5, verseRef: 'Ин 19:18', contextPhrase: 'ἐντεῦθεν καὶ ἐντεῦθεν', contextRu: 'с той и с другой стороны' },
  { lemma: 'μέσος', textForm: 'μέσον', translation: 'посередине, среди', frequency: 58, verseRef: 'Ин 19:18', contextPhrase: 'μέσον δὲ τὸν Ἰησοῦν', contextRu: 'а посреди Иисуса' },
  { lemma: 'τίτλος', textForm: 'τίτλον', translation: 'надпись, дощечка с надписью', frequency: 2, verseRef: 'Ин 19:19', contextPhrase: 'ἔγραψεν δὲ καὶ τίτλον', contextRu: 'написал же и надпись' },
  { lemma: 'γράφω', textForm: 'γεγραμμένον / ἔγραψα / γέγραφα', translation: 'написано, написал', frequency: 191, verseRef: 'Ин 19:19', contextPhrase: 'ἔγραψεν δὲ καὶ τίτλον', contextRu: 'написал же и надпись' },
  { lemma: 'ἀναγινώσκω', textForm: 'ἀνέγνωσαν', translation: 'читали, прочли', frequency: 32, verseRef: 'Ин 19:20', contextPhrase: 'τοῦτον οὖν τὸν τίτλον πολλοὶ ἀνέγνωσαν', contextRu: 'Эту надпись читали многие' },
  { lemma: 'ἐγγύς', textForm: 'ἐγγὺς', translation: 'близко, рядом', frequency: 33, verseRef: 'Ин 19:20', contextPhrase: 'ἐγγὺς ἦν ὁ τόπος', contextRu: 'близко было место' },
  { lemma: 'Ῥωμαϊστί', textForm: 'Ῥωμαϊστί', translation: 'по-латыни, на римском', frequency: 1, verseRef: 'Ин 19:20', contextPhrase: 'Ἑβραϊστί, Ῥωμαϊστί, Ἑλληνιστί', contextRu: 'по-еврейски, по-гречески, по-римски' },
  { lemma: 'Ἑλληνιστί', textForm: 'Ἑλληνιστί', translation: 'по-гречески', frequency: 5, verseRef: 'Ин 19:20', contextPhrase: 'Ἑβραϊστί, Ῥωμαϊστί, Ἑλληνιστί', contextRu: 'по-еврейски, по-гречески, по-римски' },
  { lemma: 'στρατιώτης', textForm: 'στρατιῶται / στρατιωτῶν', translation: 'воины, солдаты', frequency: 26, verseRef: 'Ин 19:23', contextPhrase: 'οἱ στρατιῶται', contextRu: 'воины' },
  { lemma: 'τέσσαρες', textForm: 'τέσσαρα', translation: 'четыре', frequency: 34, verseRef: 'Ин 19:23', contextPhrase: 'ἐποίησαν τέσσαρα μέρη', contextRu: 'сделали четыре части' },
  { lemma: 'μέρος', textForm: 'μέρος', translation: 'часть, доля', frequency: 42, verseRef: 'Ин 19:23', contextPhrase: 'τέσσαρα μέρη', contextRu: 'четыре части' },
  { lemma: 'χιτών', textForm: 'χιτῶνα', translation: 'хитон, нижняя одежда', frequency: 11, verseRef: 'Ин 19:23', contextPhrase: 'καὶ τὸν χιτῶνα', contextRu: 'и хитон' },
  { lemma: 'ἄραφος', textForm: 'ἄραφος', translation: 'бесшовный, не сшитый', frequency: 1, verseRef: 'Ин 19:23', contextPhrase: 'ἄραφος, ἐκ τῶν ἄνωθεν', contextRu: 'не сшитый, сверху' },
  { lemma: 'ἄνωθεν', textForm: 'ἄνωθεν', translation: 'сверху', frequency: 13, verseRef: 'Ин 19:23', contextPhrase: 'ἐκ τῶν ἄνωθεν', contextRu: 'сверху' },
  { lemma: 'ὑφαντός', textForm: 'ὑφαντὸς', translation: 'тканый', frequency: 1, verseRef: 'Ин 19:23', contextPhrase: 'ὑφαντὸς δι’ ὅλου', contextRu: 'весь тканый' },
  { lemma: 'ὅλος', textForm: 'δι’ ὅλου', translation: 'целиком, сплошь', frequency: 109, verseRef: 'Ин 19:23', contextPhrase: 'δι’ ὅλου', contextRu: 'целиком, сплошь' },
  { lemma: 'σχίζω', textForm: 'σχίσωμεν', translation: 'раздираем, разрываем', frequency: 11, verseRef: 'Ин 19:24', contextPhrase: 'Μὴ σχίσωμεν αὐτόν', contextRu: 'Не станем раздирать его' },
  { lemma: 'λαγχάνω', textForm: 'λάχωμεν', translation: 'бросаем жребий, получаем по жребию', frequency: 4, verseRef: 'Ин 19:24', contextPhrase: 'ἀλλὰ λάχωμεν περὶ αὐτοῦ', contextRu: 'но бросим о нем жребий' },
  { lemma: 'διαμερίζω', textForm: 'διεμερίσαντο', translation: 'разделили между собой', frequency: 11, verseRef: 'Ин 19:24', contextPhrase: 'Διεμερίσαντο τὰ ἱμάτιά μου', contextRu: 'Разделили ризы Мои' },
  { lemma: 'ἱματισμός', textForm: 'ἱματισμόν', translation: 'одежда, облачение', frequency: 5, verseRef: 'Ин 19:24', contextPhrase: 'ἐπὶ τὸν ἱματισμόν μου', contextRu: 'об одежде Моей' },
  { lemma: 'κλῆρος', textForm: 'κλῆρον', translation: 'жребий', frequency: 11, verseRef: 'Ин 19:24', contextPhrase: 'ἔβαλον κλῆρον', contextRu: 'бросали жребий' },
  { lemma: 'ἀδελφή', textForm: 'ἀδελφὴ', translation: 'сестра', frequency: 26, verseRef: 'Ин 19:25', contextPhrase: 'καὶ ἡ ἀδελφὴ τῆς μητρὸς αὐτοῦ', contextRu: 'и сестра Матери Его' },
  { lemma: 'ἴδιος', textForm: 'ἴδια', translation: 'свой дом, к себе', frequency: 113, verseRef: 'Ин 19:27', contextPhrase: 'εἰς τὰ ἴδια', contextRu: 'к себе' },
  { lemma: 'ἤδη', textForm: 'ἤδη', translation: 'уже, теперь', frequency: 60, verseRef: 'Ин 19:28', contextPhrase: 'ἤδη πάντα τετέλεσται', contextRu: 'уже все совершилось' },
  { lemma: 'τελέω', textForm: 'τετέλεσται', translation: 'совершилось, окончено', frequency: 28, verseRef: 'Ин 19:28', contextPhrase: 'τετέλεσται', contextRu: 'совершилось' },
  { lemma: 'τελειόω', textForm: 'τελειωθῇ', translation: 'исполнилось, завершилось', frequency: 23, verseRef: 'Ин 19:28', contextPhrase: 'ἵνα τελειωθῇ ἡ γραφή', contextRu: 'да сбудется Писание' },
  { lemma: 'διψάω', textForm: 'διψῶ', translation: 'жажду', frequency: 16, verseRef: 'Ин 19:28', contextPhrase: 'Διψῶ', contextRu: 'Жажду' },
  { lemma: 'σκεῦος', textForm: 'σκεῦος', translation: 'сосуд, емкость', frequency: 23, verseRef: 'Ин 19:29', contextPhrase: 'σκεῦος ἔκειτο ὄξους μεστόν', contextRu: 'сосуд стоял, полный уксуса' },
  { lemma: 'κεῖμαι', textForm: 'ἔκειτο', translation: 'стоял, находился', frequency: 24, verseRef: 'Ин 19:29', contextPhrase: 'σκεῦος ἔκειτο', contextRu: 'сосуд стоял' },
  { lemma: 'ὄξος', textForm: 'ὄξους / ὄξος', translation: 'уксус, кислое вино', frequency: 6, verseRef: 'Ин 19:29', contextPhrase: 'ὄξους μεστόν', contextRu: 'полный уксуса' },
  { lemma: 'σπόγγος', textForm: 'σπόγγον', translation: 'губка', frequency: 3, verseRef: 'Ин 19:29', contextPhrase: 'σπόγγον οὖν μεστὸν τοῦ ὄξους', contextRu: 'губку же, полную уксуса' },
  { lemma: 'πίμπλημι', textForm: 'πλήσαντες', translation: 'наполнив, пропитав', frequency: 24, verseRef: 'Ин 19:29', contextPhrase: 'σπόγγον πλήσαντες ὄξους', contextRu: 'наполнив губку уксусом' },
  { lemma: 'ὕσσωπος', textForm: 'ὑσσώπῳ', translation: 'иссоп (стебель иссопа)', frequency: 2, verseRef: 'Ин 19:29', contextPhrase: 'ὑσσώπῳ περιθέντες', contextRu: 'наложив на иссоп' },
  { lemma: 'προσφέρω', textForm: 'προσήνεγκαν', translation: 'поднесли, принесли', frequency: 47, verseRef: 'Ин 19:29', contextPhrase: 'προσήνεγκαν αὐτοῦ τῷ στόματι', contextRu: 'поднесли к Его устам' },
  { lemma: 'στόμα', textForm: 'στόματι', translation: 'рот, уста', frequency: 78, verseRef: 'Ин 19:29', contextPhrase: 'τῷ στόματι', contextRu: 'к устам' },
  { lemma: 'κλίνω', textForm: 'κλίνας', translation: 'склонив, приклонив (голову)', frequency: 7, verseRef: 'Ин 19:30', contextPhrase: 'κλίνας τὴν κεφαλὴν', contextRu: 'преклонив главу' },
  { lemma: 'παραδίδωμι', textForm: 'παρέδωκεν', translation: 'предал (дух)', frequency: 119, verseRef: 'Ин 19:30', contextPhrase: 'παρέδωκεν τὸ πνεῦμα', contextRu: 'предал дух' },
  { lemma: 'μέγας', textForm: 'μεγάλη', translation: 'великий (великая суббота)', frequency: 196, verseRef: 'Ин 19:31', contextPhrase: 'μεγάλη ἡ ἡμέρα', contextRu: 'велик день' },
  { lemma: 'ἐρωτάω', textForm: 'ἠρώτησαν', translation: 'просили, умоляли', frequency: 63, verseRef: 'Ин 19:31', contextPhrase: 'ἠρώτησαν τὸν Πιλᾶτον', contextRu: 'просили Пилата' },
  { lemma: 'κατάγνυμι', textForm: 'κατεαγῶσιν / κατέαξαν', translation: 'перебивают, сокрушают (голени)', frequency: 4, verseRef: 'Ин 19:31', contextPhrase: 'ἵνα κατεαγῶσιν αὐτῶν τὰ σκέλη', contextRu: 'чтобы перебить у них голени' },
  { lemma: 'σκέλος', textForm: 'σκέλη', translation: 'голень, ноги', frequency: 3, verseRef: 'Ин 19:31', contextPhrase: 'τὰ σκέλη', contextRu: 'голени' },
  { lemma: 'αἴρω', textForm: 'ἀρθῶσιν / ἦρεν / ἄρῃ', translation: 'убраны, снять, унести', frequency: 100, verseRef: 'Ин 19:31', contextPhrase: 'καὶ ἀρθῶσιν', contextRu: 'и снять' },
  { lemma: 'πρῶτος', textForm: 'πρώτου', translation: 'первый', frequency: 97, verseRef: 'Ин 19:32', contextPhrase: 'τοῦ πρώτου κατέαξαν τὰ σκέλη', contextRu: 'у первого перебили голени' },
  { lemma: 'συσταυρόω', textForm: 'συσταυρωθέντος', translation: 'сораспятый', frequency: 5, verseRef: 'Ин 19:32', contextPhrase: 'τοῦ συσταυρωθέντος αὐτῷ', contextRu: 'распятого с Ним' },
  { lemma: 'κρούω / νύσσω', textForm: 'ἔνυξεν', translation: 'пронзил, проколол', frequency: 1, verseRef: 'Ин 19:34', contextPhrase: 'λόγχῃ αὐτοῦ τὴν πλευρὰν ἔνυξεν', contextRu: 'копьем пронзил Ему ребра' },
  { lemma: 'λόγχη', textForm: 'λόγχῃ', translation: 'копье', frequency: 1, verseRef: 'Ин 19:34', contextPhrase: 'λόγχῃ αὐτοῦ τὴν πλευρὰν ἔνυξεν', contextRu: 'копьем пронзил Ему ребра' },
  { lemma: 'πλευρά', textForm: 'πλευρὰν', translation: 'бок, ребра', frequency: 5, verseRef: 'Ин 19:34', contextPhrase: 'τὴν πλευρὰν', contextRu: 'ребра / бок' },
  { lemma: 'εὐθέως', textForm: 'εὐθὺς', translation: 'немедленно, тотчас', frequency: 36, verseRef: 'Ин 19:34', contextPhrase: 'εὐθὺς ἐξῆλθεν αἷμα καὶ ὕδωρ', contextRu: 'тотчас истекла кровь и вода' },
  { lemma: 'αἷμα', textForm: 'αἷμα', translation: 'кровь', frequency: 97, verseRef: 'Ин 19:34', contextPhrase: 'αἷμα καὶ ὕδωρ', contextRu: 'кровь и вода' },
  { lemma: 'ὕδωρ', textForm: 'ὕδωρ', translation: 'вода', frequency: 76, verseRef: 'Ин 19:34', contextPhrase: 'αἷμα καὶ ὕδωρ', contextRu: 'кровь и вода' },
  { lemma: 'ἀληθινός', textForm: 'ἀληθινή', translation: 'истинное, подлинное', frequency: 28, verseRef: 'Ин 19:35', contextPhrase: 'ἀληθινὴ αὐτοῦ ἐστιν ἡ μαρτυρία', contextRu: 'истинно свидетельство его' },
  { lemma: 'συντρίβω', textForm: 'συντριβήσεται', translation: 'сокрушится, переломится', frequency: 7, verseRef: 'Ин 19:36', contextPhrase: 'Ὀστοῦν οὐ συντριβήσεται', contextRu: 'Кость не сокрушится' },
  { lemma: 'ὀστοῦν', textForm: 'ὀστοῦν', translation: 'кость', frequency: 4, verseRef: 'Ин 19:36', contextPhrase: 'Ὀστοῦν οὐ συντριβήσεται', contextRu: 'Кость не сокрушится' },
  { lemma: 'ἐκκεντέω', textForm: 'ἐξεκέντησαν', translation: 'пронзили', frequency: 2, verseRef: 'Ин 19:37', contextPhrase: 'εἰς ὃν ἐξεκέντησαν', contextRu: 'на Того, Которого пронзили' },
  { lemma: 'κρύπτω', textForm: 'κεκρυμμένος', translation: 'тайный, скрывающийся', frequency: 20, verseRef: 'Ин 19:38', contextPhrase: 'κεκρυμμένος δὲ διὰ τὸν φόβον', contextRu: 'но тайный из страха' },
  { lemma: 'φόβος', textForm: 'φόβον', translation: 'страх', frequency: 47, verseRef: 'Ин 19:38', contextPhrase: 'διὰ τὸν φόβον τῶν Ἰουδαίων', contextRu: 'из страха от Иудеев' },
  { lemma: 'ἐπιτρέπω', textForm: 'ἐπέτρεψεν', translation: 'позволил, разрешил', frequency: 18, verseRef: 'Ин 19:38', contextPhrase: 'καὶ ἐπέτρεψεν ὁ Πιλᾶτος', contextRu: 'и Пилат позволил' },
  { lemma: 'πρότερος', textForm: 'πρῶτον / πρότερον', translation: 'прежде, раньше', frequency: 11, verseRef: 'Ин 19:39', contextPhrase: 'ὁ ἐλθὼν ... πρότερον', contextRu: 'приходивший прежде' },
  { lemma: 'νύξ', textForm: 'νυκτὸς', translation: 'ночь, ночью', frequency: 61, verseRef: 'Ин 19:39', contextPhrase: 'νυκτός', contextRu: 'ночью' },
  { lemma: 'φέρων', textForm: 'φέρων', translation: 'принесший, неся', frequency: 66, verseRef: 'Ин 19:39', contextPhrase: 'φέρων μίγμα σμύρνης', contextRu: 'принеся состав из смирны' },
  { lemma: 'μίγμα', textForm: 'μίγμα', translation: 'смесь', frequency: 1, verseRef: 'Ин 19:39', contextPhrase: 'μίγμα σμύρνης καὶ ἀλόης', contextRu: 'состав из смирны и алоэ' },
  { lemma: 'σμύρνα', textForm: 'σμύρνης', translation: 'смирна, мирра', frequency: 2, verseRef: 'Ин 19:39', contextPhrase: 'σμύρνης', contextRu: 'смирны' },
  { lemma: 'ἀλόη', textForm: 'ἀλόης', translation: 'алоэ', frequency: 1, verseRef: 'Ин 19:39', contextPhrase: 'ἀλόης', contextRu: 'алоэ' },
  { lemma: 'λίτρα', textForm: 'λίτρας', translation: 'литра (~327 г)', frequency: 2, verseRef: 'Ин 19:39', contextPhrase: 'ὡς λίτρας ἑκατόν', contextRu: 'около ста литр' },
  { lemma: 'ἑκατόν', textForm: 'ἑκατόν', translation: 'сто', frequency: 17, verseRef: 'Ин 19:39', contextPhrase: 'λίτρας ἑκατόν', contextRu: 'ста литр' },
  { lemma: 'ὀθόνιον', textForm: 'ὀθονίοις', translation: 'пелены, льняные полотна', frequency: 5, verseRef: 'Ин 19:40', contextPhrase: 'ἔδησαν αὐτὸ ὀθονίοις', contextRu: 'обвили Его пеленами' },
  { lemma: 'δέω', textForm: 'ἔδησαν', translation: 'обвили, связали', frequency: 43, verseRef: 'Ин 19:40', contextPhrase: 'ἔδησαν αὐτὸ ὀθονίοις', contextRu: 'обвили Его пеленами' },
  { lemma: 'ἄρωμα', textForm: 'ἀρωμάτων', translation: 'благовония, ароматы', frequency: 4, verseRef: 'Ин 19:40', contextPhrase: 'μετὰ τῶν ἀρωμάτων', contextRu: 'с благовониями' },
  { lemma: 'ἔθος', textForm: 'ἔθος', translation: 'обычай', frequency: 12, verseRef: 'Ин 19:40', contextPhrase: 'καθὼς ἔθος ἐστὶν τοῖς Ἰουδαίοις', contextRu: 'как обычай у Иудеев' },
  { lemma: 'ἐνταφιάζω', textForm: 'ἐνταφιάζειν', translation: 'погребать, готовить к погребению', frequency: 2, verseRef: 'Ин 19:40', contextPhrase: 'ἐνταφιάζειν', contextRu: 'погребать' },
  { lemma: 'κῆπος', textForm: 'κῆπος', translation: 'сад', frequency: 5, verseRef: 'Ин 19:41', contextPhrase: 'ἐν τῷ τόπῳ ... κῆπος', contextRu: 'на том месте ... сад' },
  { lemma: 'μνημεῖον', textForm: 'μνημεῖον', translation: 'гробница, памятник', frequency: 40, verseRef: 'Ин 19:41', contextPhrase: 'ἐν τῷ κήπῳ μνημεῖον καινόν', contextRu: 'в саду гробница новая' },
  { lemma: 'καινός', textForm: 'καινόν', translation: 'новый', frequency: 42, verseRef: 'Ин 19:41', contextPhrase: 'μνημεῖον καινόν', contextRu: 'гробница новая' },
  { lemma: 'οὐδέπω', textForm: 'οὐδέπω', translation: 'еще никто, никогда', frequency: 28, verseRef: 'Ин 19:41', contextPhrase: 'οὐδέπω οὐδεὶς ἐτέθη', contextRu: 'еще никто не был положен' },
  { lemma: 'τίθημι', textForm: 'ἐτέθη', translation: 'положен, погребен', frequency: 100, verseRef: 'Ин 19:41', contextPhrase: 'οὐδέπω οὐδεὶς ἐτέθη', contextRu: 'никто не был положен' },
];
