export const JOHN_CHAPTER_21_WORDS_RAW = [
  { lemma: 'φανερόω', textForm: 'ἐφανέρωσεν / φανερωθεὶς', translation: 'являю, делаю явным', frequency: 49, verseRef: 'Ин 21:1', contextPhrase: 'ἐφανέρωσεν ἑαυτὸν πάλιν', contextRu: 'опять явил Себя' },
  { lemma: 'θάλασσα', textForm: 'θαλάσσης', translation: 'море, озеро', frequency: 91, verseRef: 'Ин 21:1', contextPhrase: 'ἐπὶ τῆς θαλάσσης τῆς Τιβεριάδος', contextRu: 'при море Тивериадском' },
  { lemma: 'ὁμοῦ', textForm: 'ὁμοῦ', translation: 'вместе', frequency: 4, verseRef: 'Ин 21:2', contextPhrase: 'Ἦσαν ὁμοῦ', contextRu: 'Были вместе' },
  { lemma: 'Δίδυμος', textForm: 'Δίδυμος', translation: 'Близнец (Дидим)', frequency: 3, verseRef: 'Ин 21:2', contextPhrase: 'ὁ λεγόμενος Δίδυμος', contextRu: 'называемый Близнец' },
  { lemma: 'ἁλιεύω', textForm: 'ἁλιεύειν', translation: 'ловлю рыбу, рыбачу', frequency: 1, verseRef: 'Ин 21:3', contextPhrase: 'Ὑπάγω ἁλιεύειν', contextRu: 'Иду ловить рыбу' },
  { lemma: 'ἐμβαίνω', textForm: 'ἐνέβησαν', translation: 'сели в лодку, вошли', frequency: 18, verseRef: 'Ин 21:3', contextPhrase: 'καὶ ἐνέβησαν εἰς τὸ πλοῖον', contextRu: 'и вошли в лодку' },
  { lemma: 'πλοῖον', textForm: 'πλοῖον', translation: 'лодка, судно', frequency: 68, verseRef: 'Ин 21:3', contextPhrase: 'εἰς τὸ πλοῖον', contextRu: 'в лодку' },
  { lemma: 'νύξ', textForm: 'νυκτὶ', translation: 'ночь, ночью', frequency: 61, verseRef: 'Ин 21:3', contextPhrase: 'ἐν ἐκείνῃ τῇ νυκτὶ', contextRu: 'в ту ночь' },
  { lemma: 'πιάζω', textForm: 'ἐπίασαν / ἐπιάσατε', translation: 'поймали, схватили', frequency: 12, verseRef: 'Ин 21:3', contextPhrase: 'οὐδὲν ἐπίασαν', contextRu: 'ничего не поймали' },
  { lemma: 'πρωΐα', textForm: 'πρωΐας', translation: 'утро, на рассвете', frequency: 4, verseRef: 'Ин 21:4', contextPhrase: 'πρωΐας δὲ ἤδη γενομένης', contextRu: 'А когда уже настало утро' },
  { lemma: 'αἰγιαλός', textForm: 'αἰγιαλόν', translation: 'берег, прибрежная полоса', frequency: 6, verseRef: 'Ин 21:4', contextPhrase: 'ἔστη Ἰησοῦς εἰς τὸν αἰγιαλόν', contextRu: 'Иисус стоял на берегу' },
  { lemma: 'παιδίον', textForm: 'παιδία', translation: 'дети, ребята', frequency: 52, verseRef: 'Ин 21:5', contextPhrase: 'Παιδία, μή τι προσφάγιον ἔχετε;', contextRu: 'Дети! есть ли у вас какая пища?' },
  { lemma: 'προσφάγιον', textForm: 'προσφάγιον', translation: 'рыба, еда к хлебу', frequency: 1, verseRef: 'Ин 21:5', contextPhrase: 'μή τι προσφάγιον ἔχετε;', contextRu: 'есть ли у вас какая пища?' },
  { lemma: 'βάλλω', textForm: 'βάλετε / ἔβαλον', translation: 'забросьте, закинули', frequency: 122, verseRef: 'Ин 21:6', contextPhrase: 'Βάλετε εἰς τὰ δεξιὰ', contextRu: 'Закиньте по правую сторону' },
  { lemma: 'δεξιός', textForm: 'δεξιὰ', translation: 'правая (сторона)', frequency: 54, verseRef: 'Ин 21:6', contextPhrase: 'εἰς τὰ δεξιὰ μέρη', contextRu: 'по правую сторону' },
  { lemma: 'δίκτυον', textForm: 'δίκτυον / δικτύων / δικτύῳ', translation: 'сеть', frequency: 12, verseRef: 'Ин 21:6', contextPhrase: 'βάλετε ... τὸ δίκτυον', contextRu: 'закиньте ... сеть' },
  { lemma: 'εὑρίσκω', textForm: 'εὑρήσετε', translation: 'найдете', frequency: 176, verseRef: 'Ин 21:6', contextPhrase: 'καὶ εὑρήσετε', contextRu: 'и поймаете' },
  { lemma: 'ἕλκω', textForm: 'ἑλκύσαι / εἵλκυσεν', translation: 'тянуть, вытащить', frequency: 8, verseRef: 'Ин 21:6', contextPhrase: 'οὐκέτι αὐτὸ ἑλκύσαι ἴσχυον', contextRu: 'уже не могли вытащить ее' },
  { lemma: 'πλῆθος', textForm: 'πλήθους', translation: 'множество, изобилие', frequency: 32, verseRef: 'Ин 21:6', contextPhrase: 'ἀπὸ τοῦ πλήθους τῶν ἰχθύων', contextRu: 'от множества рыбы' },
  { lemma: 'ἰχθύς', textForm: 'ἰχθύων / ἰχθύας / ἰχθύων', translation: 'рыба', frequency: 20, verseRef: 'Ин 21:6', contextPhrase: 'τῶν ἰχθύων', contextRu: 'рыбы' },
  { lemma: 'φιλέω', textForm: 'ἐφίλει', translation: 'любил', frequency: 25, verseRef: 'Ин 21:7', contextPhrase: 'ὃν ἐφίλει ὁ Ἰησοῦς', contextRu: 'которого любил Иисус' },
  { lemma: 'ἐπενδύτης', textForm: 'ἐπενδύτην', translation: 'верхняя одежда, накидка', frequency: 1, verseRef: 'Ин 21:7', contextPhrase: 'τὸν ἐπενδύτην διεζώσατο', contextRu: 'опоясался одеждою' },
  { lemma: 'διαζώννυμι', textForm: 'διεζώσατο', translation: 'препоясался, оделся', frequency: 3, verseRef: 'Ин 21:7', contextPhrase: 'τὸν ἐπενδύτην διεζώσατο', contextRu: 'опоясался одеждою' },
  { lemma: 'γυμνός', textForm: 'γυμνός', translation: 'нагой, раздетый', frequency: 15, verseRef: 'Ин 21:7', contextPhrase: 'ἦν γὰρ γυμνός', contextRu: 'ибо он был наг' },
  { lemma: 'πλοιάριον', textForm: 'πλοιαρίῳ', translation: 'малая лодка, ялик', frequency: 5, verseRef: 'Ин 21:8', contextPhrase: 'τῷ πλοιαρίῳ ἦλθον', contextRu: 'приплыли в лодке' },
  { lemma: 'μακράν', textForm: 'μακρὰν', translation: 'далеко', frequency: 10, verseRef: 'Ин 21:8', contextPhrase: 'οὐ γὰρ ἦσαν μακρὰν', contextRu: 'ибо были недалеко' },
  { lemma: 'πῆχυς', textForm: 'πηχῶν', translation: 'локоть (мера ~45 см)', frequency: 4, verseRef: 'Ин 21:8', contextPhrase: 'ὡς ἀπὸ πηχῶν διακοσίων', contextRu: 'около двухсот локтей' },
  { lemma: 'διακόσιοι', textForm: 'διακοσίων', translation: 'двести', frequency: 8, verseRef: 'Ин 21:8', contextPhrase: 'πηχῶν διακοσίων', contextRu: 'двухсот локтей' },
  { lemma: 'σύρω', textForm: 'σύροντες', translation: 'волоча, таща за собой', frequency: 5, verseRef: 'Ин 21:8', contextPhrase: 'σύροντες τὸ δίκτυον', contextRu: 'таща сеть' },
  { lemma: 'ἀποβαίνω', textForm: 'ἀπέβησαν', translation: 'сошли (на землю), высадились', frequency: 4, verseRef: 'Ин 21:9', contextPhrase: 'Ὡς οὖν ἀπέβησαν εἰς τὴν γῆν', contextRu: 'Когда же вышли на землю' },
  { lemma: 'ἀνθρακιά', textForm: 'ἀνθρακιὰν', translation: 'горящие угли, костер', frequency: 2, verseRef: 'Ин 21:9', contextPhrase: 'βλέπουσιν ἀνθρακιὰν κειμένην', contextRu: 'видят разложенный огонь' },
  { lemma: 'κεῖμαι', textForm: 'κειμένην', translation: 'лежащий, стоящий', frequency: 24, verseRef: 'Ин 21:9', contextPhrase: 'ἀνθρακιὰν κειμένην', contextRu: 'разложенный огонь' },
  { lemma: 'ὀψάριον', textForm: 'ὀψάριον / ὀψαρίων', translation: 'рыба, рыбка', frequency: 5, verseRef: 'Ин 21:9', contextPhrase: 'καὶ ὀψάριον ἐπικείμενον', contextRu: 'и на нем лежащую рыбу' },
  { lemma: 'ἄρτος', textForm: 'ἄρτον', translation: 'хлеб', frequency: 97, verseRef: 'Ин 21:9', contextPhrase: 'καὶ ἄρτον', contextRu: 'и хлеб' },
  { lemma: 'φέρω', textForm: 'ἐνέγκατε', translation: 'принесите', frequency: 66, verseRef: 'Ин 21:10', contextPhrase: 'Ἐνέγκατε ἀπὸ τῶν ὀψαρίων', contextRu: 'Принесите рыбы' },
  { lemma: 'ἀναβαίνω', textForm: 'ἀνέβη', translation: 'взошел, вошел (в лодку)', frequency: 82, verseRef: 'Ин 21:11', contextPhrase: 'ἀνέβη οὖν Σίμων Πέτρος', contextRu: 'Симон Петр пошел' },
  { lemma: 'ἑκατόν', textForm: 'ἑκατόν', translation: 'сто', frequency: 17, verseRef: 'Ин 21:11', contextPhrase: 'ἑκατὸν πεντήκοντα τριῶν', contextRu: 'сто пятьдесят три' },
  { lemma: 'πεντήκοντα', textForm: 'πεντήκοντα', translation: 'пятьдесят', frequency: 7, verseRef: 'Ин 21:11', contextPhrase: 'ἑκατὸν πεντήκοντα τριῶν', contextRu: 'сто пятьдесят три' },
  { lemma: 'τρεῖς', textForm: 'τριῶν', translation: 'три', frequency: 68, verseRef: 'Ин 21:11', contextPhrase: 'ἑκατὸν πεντήκοντα τριῶν', contextRu: 'сто пятьдесят три' },
  { lemma: 'τοσοῦτος', textForm: 'τοσούτων', translation: 'столь многих, стольких', frequency: 20, verseRef: 'Ин 21:11', contextPhrase: 'καὶ τοσούτων ὄντων', contextRu: 'и при таком множестве' },
  { lemma: 'σχίζω', textForm: 'ἐσχίσθη', translation: 'порвалась, разорвалась', frequency: 11, verseRef: 'Ин 21:11', contextPhrase: 'οὐκ ἐσχίσθη τὸ δίκτυον', contextRu: 'не прорвалась сеть' },
  { lemma: 'δεῦτε', textForm: 'δεῦτε', translation: 'придите, ступайте', frequency: 12, verseRef: 'Ин 21:12', contextPhrase: 'Δεῦτε ἀριστήσατε', contextRu: 'Придите, обедайте' },
  { lemma: 'ἀριστάω', textForm: 'ἀριστήσατε / ἠρίστησαν', translation: 'завтракайте, пообедали', frequency: 3, verseRef: 'Ин 21:12', contextPhrase: 'Δεῦτε ἀριστήσατε', contextRu: 'Придите, обедайте' },
  { lemma: 'τολμάω', textForm: 'ἐτόλμα', translation: 'смел, отваживался', frequency: 16, verseRef: 'Ин 21:12', contextPhrase: 'οὐδεὶς δὲ ἐτόλμα τῶν μαθητῶν', contextRu: 'Никто же из учеников не смел' },
  { lemma: 'ἐξετάζω', textForm: 'ἐξετάσαι', translation: 'расспрашивать, выведывать', frequency: 3, verseRef: 'Ин 21:12', contextPhrase: 'ἐξετάσαι αὐτόν· Σὺ τίς εἶ;', contextRu: 'спросить Его: кто Ты?' },
  { lemma: 'τρίτος', textForm: 'τρίτον', translation: 'третий, в третий раз', frequency: 46, verseRef: 'Ин 21:14', contextPhrase: 'Τοῦτο ἤδη τρίτον', contextRu: 'Это уже в третий раз' },
  { lemma: 'ἐγείρω', textForm: 'ἐγερθεὶς', translation: 'воскресший, вставший', frequency: 144, verseRef: 'Ин 21:14', contextPhrase: 'ἐγερθεὶς ἐκ νεκρῶν', contextRu: 'воскреснув из мертвых' },
  { lemma: 'ἀγαπάω', textForm: 'ἀγαπᾷς / ἀγαπῶ', translation: 'любишь, люблю', frequency: 143, verseRef: 'Ин 21:15', contextPhrase: 'ἀγαπᾷς με πλέον τούτων;', contextRu: 'любишь ли ты Меня больше, нежели они?' },
  { lemma: 'πλείων', textForm: 'πλέον', translation: 'больше, сильнее', frequency: 58, verseRef: 'Ин 21:15', contextPhrase: 'πλέον τούτων;', contextRu: 'больше, нежели они?' },
  { lemma: 'βόσκω', textForm: 'βόσκε', translation: 'паси, корми', frequency: 9, verseRef: 'Ин 21:15', contextPhrase: 'Βόσκε τὰ ἀρνία μου', contextRu: 'Паси агнцев Моих' },
  { lemma: 'ἀρνίον', textForm: 'ἀρνία', translation: 'агнцы, ягнята', frequency: 30, verseRef: 'Ин 21:15', contextPhrase: 'τὰ ἀρνία μου', contextRu: 'агнцев Моих' },
  { lemma: 'δεύτερος', textForm: 'δεύτερον', translation: 'второй раз', frequency: 43, verseRef: 'Ин 21:16', contextPhrase: 'πάλιν δεύτερον', contextRu: 'опять, в другой раз' },
  { lemma: 'ποιμαίνω', textForm: 'ποίμαινε', translation: 'паси, опекай', frequency: 11, verseRef: 'Ин 21:16', contextPhrase: 'Ποίμαινε τὰ πρόβατά μου', contextRu: 'Паси овец Моих' },
  { lemma: 'πρόβατον', textForm: 'πρόβατα / προβάτια', translation: 'овцы', frequency: 39, verseRef: 'Ин 21:16', contextPhrase: 'τὰ πρόβατά μου', contextRu: 'овец Моих' },
  { lemma: 'λυπέω', textForm: 'ἐλυπήθη', translation: 'опечалился', frequency: 26, verseRef: 'Ин 21:17', contextPhrase: 'ἐλυπήθη ὁ Πέτρος', contextRu: 'Петр опечалился' },
  { lemma: 'νεώτερος', textForm: 'νεώτερος', translation: 'моложе, юноша', frequency: 11, verseRef: 'Ин 21:18', contextPhrase: 'ὅτε ἦς νεώτερος', contextRu: 'когда ты был молод' },
  { lemma: 'ζώννυμι', textForm: 'ἐζώννυες / ζώσει', translation: 'препоясывал сам, опояшет', frequency: 2, verseRef: 'Ин 21:18', contextPhrase: 'ἐζώννυες σεαυτὸν', contextRu: 'то препоясывался сам' },
  { lemma: 'γηράσκω', textForm: 'γηράσῃς', translation: 'состаришься', frequency: 2, verseRef: 'Ин 21:18', contextPhrase: 'ὅταν δὲ γηράσῃς', contextRu: 'а когда состаришься' },
  { lemma: 'ἐκτείνω', textForm: 'ἐκτενεῖς', translation: 'прострешь, протянешь', frequency: 16, verseRef: 'Ин 21:18', contextPhrase: 'ἐκτενεῖς τὰς χεῖράς σου', contextRu: 'то прострешь руки твои' },
  { lemma: 'σημαίνω', textForm: 'σημαίνων', translation: 'указывая, давая знать', frequency: 6, verseRef: 'Ин 21:19', contextPhrase: 'σημαίνων ποίῳ θανάτῳ', contextRu: 'давая разуметь, какою смертью' },
  { lemma: 'ποῖος', textForm: 'ποίῳ', translation: 'какой, какого рода', frequency: 33, verseRef: 'Ин 21:19', contextPhrase: 'ποίῳ θανάτῳ', contextRu: 'какою смертью' },
  { lemma: 'δοξάζω', textForm: 'δοξάσει', translation: 'прославит', frequency: 61, verseRef: 'Ин 21:19', contextPhrase: 'δοξάσει τὸν θεόν', contextRu: 'прославит Бога' },
  { lemma: 'ἐπιστρέφω', textForm: 'ἐπιστραφεὶς', translation: 'обернувшись, повернувшись', frequency: 36, verseRef: 'Ин 21:20', contextPhrase: 'Ἐπιστραφεὶς ὁ Πέτρος βλέπει', contextRu: 'Петр же, обратившись, видит' },
  { lemma: 'ἀνάκειμαι', textForm: 'ἀνέπεσεν', translation: 'возлежал, припал', frequency: 12, verseRef: 'Ин 21:20', contextPhrase: 'ὃς καὶ ἀνέπεσεν ἐν τῷ δείπνῳ', contextRu: 'который на вечери, приклонившись' },
  { lemma: 'δεῖπνον', textForm: 'δείπνῳ', translation: 'вечеря, ужин', frequency: 16, verseRef: 'Ин 21:20', contextPhrase: 'ἐν τῷ δείπνῳ', contextRu: 'на вечери' },
  { lemma: 'στῆθος', textForm: 'στῆθος', translation: 'грудь', frequency: 5, verseRef: 'Ин 21:20', contextPhrase: 'ἐπὶ τὸ στῆθος αὐτοῦ', contextRu: 'к груди Его' },
  { lemma: 'παραδίδωμι', textForm: 'παραδιδούς', translation: 'предающий', frequency: 119, verseRef: 'Ин 21:20', contextPhrase: 'τίς ἐστιν ὁ παραδιδούς σε;', contextRu: 'кто предаст Тебя?' },
  { lemma: 'χωρέω', textForm: 'χωρῆσαι', translation: 'вместить', frequency: 10, verseRef: 'Ин 21:25', contextPhrase: 'τὸν κόσμον χωρῆσαι τὰ γραφόμενα', contextRu: 'самому миру не вместить бы' },
  { lemma: 'βιβλίον', textForm: 'βιβλία', translation: 'книги, свитки', frequency: 34, verseRef: 'Ин 21:25', contextPhrase: 'τὰ γραφόμενα βιβλία', contextRu: 'написанных книг' },
];
